### PR TITLE
Workaround safari webgl bug

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by TristanWright** [comment]
does this fix #11?

**Comment by scottwittenburg** [comment]
Yes, though It's a workaround we should remove when the safari bug is fixed, which is why the fix is so narrowly targeted.  Other projects have encountered the same problem:

https://github.com/mapbox/mapbox-gl-js/issues/2986

**Comment by TristanWright** [comment]
Did you test this on mobile safari or just desktop?

**Comment by TristanWright** [comment]
nevermind, works here.

**Comment by scottwittenburg** [comment]
Seb tried it on mobile safari, but I only tested on desktop.

**Pull request merged**
